### ISSUE TITLE
index issue with ESAC E_pow_su__CL_SP_WHI

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/server-java#13]
This appears to have the channels off-by-one index:

vap+hapi:https://cottagesystems.com/server/esac/hapi?id=CL_SP_WHI&parameters=time_tags__CL_SP_WHI,E_pow_su__CL_SP_WHI&timerange=2012-12-27

I noticed a fill value of 32768 present, which is consistent with the next parameters but not E_pow_su__CL_SP_WHI, and the last one of the parameters raises a 500 error.

**Comment by jbfaden** [comment]
I think these are possibly inconsistent on the server.  

During the info request:
https://csa.esac.esa.int/csa-sl-tap/data?retrieval_type=HEADER&DATASET_ID=CL_SP_WHI&FORCEPACK=false


During the data request: 
https://csa.esac.esa.int/csa-sl-tap/data?RETRIEVAL_TYPE=product&RETRIEVAL_ACCESS=streamed&DATASET_ID=CL_SP_WHI&START_DATE=2012-12-31T00:00:00Z&END_DATE=2012-12-31T23:59:59Z

**Comment by rweigel** [comment]
When it is ready, can try online with

https://hapi-server.org/servers/#server=https://cottagesystems.com/server/esac/hapi/

**Comment by jbfaden** [comment]
That's what I'm doing now :).   There's work to do, for sure, but it seems like it's working. Some of these datasets are quite large and there's no way to know what a reasonable request size is.  Or do you look at the cadence at all?  I don't think Autoplot does, and it should.

**Comment by jbfaden** [comment]
Anastasia pointed out that non-record-varying data has a DATA node with the constant value.  I'm coding for this now.
